#!/bin/bash

set -e

# Colors
GREEN="\e[32m"
RED="\e[31m"
CYAN="\e[36m"
RESET="\e[0m"

# Variables
MAILCOW_DIR="/opt/mailcow-dockerized"
TIMEZONE="Asia/Riyadh"
MAILCOW_DOMAIN=${1:-"mail.local"}

echo -e "${CYAN}🔧 Starting Mailcow Installation...${RESET}"

# Clone Mailcow if needed
if [ ! -d "$MAILCOW_DIR" ]; then
  echo -e "${GREEN}📥 Cloning Mailcow Dockerized...${RESET}"
  git clone https://github.com/mailcow/mailcow-dockerized "$MAILCOW_DIR"
fi

cd "$MAILCOW_DIR" || { echo -e "${RED}❌ Failed to enter $MAILCOW_DIR directory.${RESET}"; exit 1; }

# Copy config and set domain
cp -f mailcow.conf.example mailcow.conf

if [ -z "$MAILCOW_DOMAIN" ]; then
  read -p "🌐 Enter your Mailcow domain (e.g., mail.example.com): " MAILCOW_DOMAIN
fi

if [ -z "$MAILCOW_DOMAIN" ]; then
  echo -e "${RED}❌ Error: Domain name is required.${RESET}"
  exit 1
fi

sed -i "s/^MAILCOW_HOSTNAME=.*/MAILCOW_HOSTNAME=$MAILCOW_DOMAIN/" mailcow.conf
sed -i "s|^TZ=.*|TZ=$TIMEZONE|" mailcow.conf

echo -e "${GREEN}📡 Pulling Docker images...${RESET}"
docker compose pull
docker compose up -d

# UFW Setup
echo -e "${GREEN}🔐 Configuring UFW...${RESET}"
sudo ufw allow OpenSSH
sudo ufw allow 80,443/tcp
sudo ufw allow 25,465,587/tcp
sudo ufw allow 993,995/tcp
sudo ufw --force enable

# Fail2ban Setup
echo -e "${GREEN}🛡️ Installing and configuring fail2ban...${RESET}"
sudo apt update && sudo apt install -y fail2ban

sudo tee /etc/fail2ban/jail.local > /dev/null <<EOF
[sshd]
enabled = true
port    = ssh
logpath = %(sshd_log)s
backend = systemd
bantime = 1h
findtime = 10m
maxretry = 5
EOF

sudo systemctl restart fail2ban
sudo systemctl enable fail2ban

# Optional DNS Resolver
echo -e "${CYAN}🌐 Configuring local DNS resolver... (optional)${RESET}"
sudo apt install -y unbound
sudo systemctl enable unbound
sudo systemctl start unbound

# DNS Records Recommendation
echo -e "${CYAN}📌 Recommended DNS records for $MAILCOW_DOMAIN${RESET}"
echo -e "${CYAN}---------------------------------------------------------${RESET}"
echo -e "${GREEN}A record:${RESET}            $MAILCOW_DOMAIN -> your_server_ip"
echo -e "${GREEN}MX record:${RESET}           $MAILCOW_DOMAIN -> priority 10"
echo -e "${GREEN}SPF record (TXT):${RESET}     v=spf1 mx ~all"
echo -e "${GREEN}DKIM record (TXT):${RESET}    Will be generated by Mailcow"
echo -e "${GREEN}DMARC record (TXT):${RESET}   _dmarc.$MAILCOW_DOMAIN -> v=DMARC1; p=none; rua=mailto:postmaster@$MAILCOW_DOMAIN"
echo -e "${GREEN}Autoconfig (CNAME):${RESET}   autoconfig.$MAILCOW_DOMAIN -> $MAILCOW_DOMAIN"
echo -e "${CYAN}---------------------------------------------------------${RESET}"

# Final Message
echo -e "${GREEN}✅ Mailcow is now running at: https://$MAILCOW_DOMAIN${RESET}"
echo -e "${GREEN}🎉 Installation completed successfully!${RESET}"

cd ~
